### ISSUE TITLE
improve image uploading

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#10]
demo:
https://easy-crop.netlify.app/

code:
https://www.npmjs.com/package/react-easy-crop

**Comment by apala7778** [comment]
hey i can design and improve image uploading styling. can i get started?

**Comment by albjeremias** [comment]
> hey i can design and improve image uploading styling. can i get started?

yes you are welcome :) We are also in telegram or mastodon if you want to chat.


this issue is related:
https://github.com/helpbuttons/helpbuttons/issues/11


Here is the component:
https://github.com/helpbuttons/helpbuttons/blob/main/web/src/elements/Fields/FieldImageUpload/index.tsx

And here is a parent component using it:
https://github.com/helpbuttons/helpbuttons/blob/main/web/src/pages/ButtonNew/index.tsx#L108
