### ISSUE TITLE
[BUG] Error message when success registration

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#1006]
### 🐞 Describe the Bug

Users report confused when they press register button twice very fast in the register form. The registration success but the app displays an error "already registered" so they think it didn't work

---

### 🔍 Steps to Reproduce

1. Go to Register, complete the form
2. Click on Register twice

---

### 🤔 Expected Behavior

Avoid the error after press register, wait to show the message so it can show suceess

**Comment by albjeremias** [comment]
the issue is that the submit button should be disabled when pressed!

**Comment by watchoutfreedom** [comment]
ok!

**Comment by albjeremias** [comment]
sorry, i tested it now.. this is not possible. i dont understand how this happens. need more testing or better report

**Comment by albjeremias** [comment]
1c35e19a4ab094d8f63bdc439af9466f781a0681
