### ISSUE TITLE
[BUG] Swipe helpbuttons error

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#1009]
### 🐞 Describe the Bug

Helpbutton keeps the same ribbon up on the button card when sliding / swipe on mobile .

Also the app breaks if you open the helpbutton image and then swipe (when we have the image slider ready it would swap between images) . I would recommend move the swipe functionality to another branch till we have the animation and these bugs ready in a PR

---

**Comment by albjeremias** [comment]
ok, i will disable for now

**Comment by albjeremias** [comment]
08c4eb3861e5becb785ac9d74f0ad9b83ff74420
