### ISSUE TITLE
jsx css classes spread on elements

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#110]
weird jsx classes appear on lots of divs on rendering. 

No idea why they are there but may be a problem for css,

![Captura de Pantalla 2023-04-14 a las 16 43 59](https://user-images.githubusercontent.com/23015314/232077094-bedf3165-515f-4d08-9be5-30e912b5d7e6.jpg)

**Comment by albjeremias** [comment]
i have no idea what is this.

**Comment by albjeremias** [comment]
this is the problem:
https://github.com/helpbuttons/helpbuttons/blob/main/web/src/pages/HomeInfo/index.tsx#L78-L82

**Comment by albjeremias** [comment]
a8a689342a81502aeec37587b11d6e6dcf0bb5a1
