### ISSUE TITLE
Allow other users to leave a message in your button, event if there are no other posts. 

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#113]
It should allow other users to leave messages on the buttons when there are no posts. Those posts initiated by other users would only be visible for the owner of the button and the sender.

**Comment by albjeremias** [comment]
this can be extremely confusing. i think it would be better to having flashing things asking for the user of the button to create a first post.

**Comment by watchoutfreedom** [comment]
Better create a first post right after the creation of the button in that case: ¨User created this button at DATE, leave a comment if you want¨

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/pull/175 :confetti_ball:
