### ISSUE TITLE
Can't edit network base location 

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#138]
Edit form not working

**Comment by albjeremias** [comment]
i dont understand this issue... can you please explain @watchoutfreedom ?

**Comment by albjeremias** [comment]
the issue is that when click on "Explore" jump to selected network place.. 
when going back, get from the store the place

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/commit/0bbb0d75404ee9800b0f10cb3edc110541119bab
