### ISSUE TITLE
Text gone in menus and home info

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#14]
What did you expect?
Text in navigation menus, network name, and serach field header is gone

What is happening?
Not sure, html tag exists but it´s empty

How u think it can be solved?
May be an issue with the translations?

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/pull/19/commits/c1480a87fece033406ea9626ab1d913d4d00234e fixes it!
