### ISSUE TITLE
List Tab stopped working

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#15]
What did you expect?
When you click in the tab on top of the list section, it should hide/show the list to leave more space to the map

What is happening?
You click but nothing happens, it was working in the pas but not now.

How u think it can be solved?
May be that the function is no longer linked to the component?

**Comment by albjeremias** [comment]
fixed: https://github.com/helpbuttons/helpbuttons/pull/19/commits/6fd45d00f6f9b891e848a65c704482fd59285016
