### ISSUE TITLE
Cannot access button info clicking on map

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#17]
What did you expect?
Acces Buttonfile clicking on the buttoncard on list or on map. It also doesn´t show button info when clicking on it over map. 
What is happening?
Doesn´t show info or button. file when clickng in cardsboth in list and on map markers.
How u think it can be solved?
I don´t know

**Comment by albjeremias** [comment]
fixed:
https://github.com/helpbuttons/helpbuttons/commit/894910f46d29dd5f14721f4f2ca61c1dc8ddbfa0
