### ISSUE TITLE
Search button in home should lead to Explore view with filters opened

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#182]
Search button on home view doesn't have the data linked, and also should lead to the explore view with the filters opened so it complete the functionality. 

When there are no filters selected by types, it should say "All types" or disappear from the search field.

There are some css overflow problems we need to fix also.

**Comment by albjeremias** [comment]
implemented here:
https://github.com/helpbuttons/helpbuttons/pull/202
