### ISSUE TITLE
Allow rename "helpbuttons" for other

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#184]
Allw rename the default helpbuttons name so it is easier to the user to understand. It can be "botones de ayuda" , "publicaciones", "viajes", "colaboraciones", "permaculters", depending on the network usage

**Comment by albjeremias** [comment]
can you please list all the places where the word helpbuttons appears? 

to implement this.. maybe in the translations files we can use something like: __networkButtonName__ and replace this with a config/db variable

**Comment by watchoutfreedom** [comment]
> can you please list all the places where the word helpbuttons appears?
> 
> to implement this.. maybe in the translations files we can use something like: **networkButtonName** and replace this with a config/db variable

yes that's exactly what I meant thanks
