### ISSUE TITLE
User profile description and data is uncomplete

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#185]
Remove the Description: from the description, allow tags, replace the profile created field

**Comment by albjeremias** [comment]
im sorry, but can you please be more descriptive about your issues?

**Comment by watchoutfreedom** [comment]
![Captura de Pantalla 2023-07-09 a las 16 39 03](https://github.com/helpbuttons/helpbuttons/assets/23015314/a1d6366d-6fe6-4532-b287-0a155b4cba4e)

**Comment by watchoutfreedom** [comment]
I refer to the top fields. Description: and the profile created date

**Comment by albjeremias** [comment]
all the fields are there.. you just need to edit your profile.
