### ISSUE TITLE
In the Activity window, make every post a link to the button

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#186]

**Comment by albjeremias** [comment]
which event is not linked to a button?

**Comment by watchoutfreedom** [comment]
sorry comments and posts publications are not linked to the button (ideal behaviour would be to scroll and show the comment or the post )

**Comment by albjeremias** [comment]
> sorry comments and posts publications are not linked to the button (ideal behaviour would be to scroll and show the comment or the post ) but that's for future

i dont understand.

**Comment by watchoutfreedom** [comment]
Comments and post notifications in activity window are not linked to the button. I can update this
