### ISSUE TITLE
After register, the screen freezes in blank, needs to reload

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#190]
After register throws an error and needs to reload to go to home again
https://resiste.barrososemminas.org/HomeInfo

![Captura de Pantalla 2023-07-09 a las 16 30 14](https://github.com/helpbuttons/helpbuttons/assets/23015314/cab1f5de-b979-4efa-9027-65318e9503ef)

**Comment by albjeremias** [comment]
please can we only report bugs on the dev branch? it's a mess to report bugs from different instances. thanks.
