### ISSUE TITLE
ERROR When disable all button types and apply filters,

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#191]
If you disable all button types and apply filters, the app crashes

![Captura de Pantalla 2023-07-09 a las 16 36 51](https://github.com/helpbuttons/helpbuttons/assets/23015314/258d8474-e8ba-49b5-9dd8-d64d3b0505ac)

**Comment by albjeremias** [comment]
I dont understand. can you please explain step by step?

**Comment by albjeremias** [comment]
cant replicate here.. can u explain step by step?

**Comment by watchoutfreedom** [comment]
may be another issue , closing
