### ISSUE TITLE
Make all buttontypes filters unselected by default

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#193]
Make the filters unselected equivalent to unfiltered search, so initially all filters are unselected. And show "All types" on top nevheader
![Captura de Pantalla 2023-07-10 a las 13 28 34](https://github.com/helpbuttons/helpbuttons/assets/23015314/20552486-d7ef-48c7-b6a4-ba2057575381)

**Comment by albjeremias** [comment]
ahm, how do you come back to "all the button types"? i don't get it. why they are not selected? that makes it super complicated to understand and to code it... what u may want is that it says "all button types" on top.. but really this is a real mess to implement. i dont think its a good idea to do it.

**Comment by watchoutfreedom** [comment]
We can discuss the logic the logic but tipically in other sites filters are not selected by default, and you choose the types to filter, not the other way around. But again this may be not important for now

**Comment by albjeremias** [comment]
ok, can u send me some examples maybe i can understand it better ur proposal :)

**Comment by albjeremias** [comment]
done
