### ISSUE TITLE
New merge search not working

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#211]
Button description and title has keyword, bit search doesnt find it

![Captura de Pantalla 2023-07-15 a las 15 10 36](https://github.com/helpbuttons/helpbuttons/assets/23015314/c1c183fb-08c8-4384-8d98-830c17a53909)

**Comment by albjeremias** [comment]
fix: 
https://github.com/helpbuttons/helpbuttons/pull/212
