### ISSUE TITLE
backend throws error not registered but session looks like initiated

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#214]
Even after reload backend, when there are no activities and you access activity section for the first time, yo see two object error, then you can conitnue to navigate normally. COnsole shows need registered but user is logged

![Captura de Pantalla 2023-07-18 a las 19 37 46](https://github.com/helpbuttons/helpbuttons/assets/23015314/3b6f4f48-0232-4bf8-87ee-927d200365f6)

**Comment by albjeremias** [comment]
please logout and login again.. if it happens again we need to research this issue.. and maybe automatic logout the user..
