### ISSUE TITLE
create a button when click in empty hexagon?

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#229]
Study the possibility of adding button in the hexagon empty when clicking it

**Comment by albjeremias** [comment]
can you please explain me the flow.. like the user presses an hexagon.. and it directly opens the buttonform with a button location centered in the hexagon? or it needs a confirmation link before showing the form?

**Comment by albjeremias** [comment]
can click empty hexagons 
top of listbuttons will have an option to create button

- bug:
 > when select hexagon, go to advanced filters, clear.. stays loading forever..
