### ISSUE TITLE
locations selected on map appear like "..."

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#237]
Many locations when selected appear with ... . Ideally we can show a general address (like the region, or city) and show an exact location when clicked in the address.
![Captura de Pantalla 2023-07-21 a las 17 09 13](https://github.com/helpbuttons/helpbuttons/assets/23015314/b9b97142-18fd-45bc-a58a-fa07b403738d)

**Comment by albjeremias** [comment]
this happens because opencage is not active, u need to setup an opencage api key.
I mean, if the app can't get the address of the coordinates, then it can't setup an address. maybe instead of the "..." you would like to put something else?
