### ISSUE TITLE
Error in access after login

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#246]
After login with email and pwd, and navigating to a button file (owned by admin) this error appears

![Captura de Pantalla 2023-07-26 a las 15 41 24](https://github.com/helpbuttons/helpbuttons/assets/23015314/b6affc09-eee0-460d-898d-f91409d53032)

**Comment by albjeremias** [comment]
what do u mean with pwd? so its a button created by an admin, and you enter as a user.. and check the button of the admin?
do u known if the button has comments or posts? 

is this localhost? or permaculture?

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/pull/251
