### ISSUE TITLE
Slow image loading in localhost and online

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#258]
slow image loading in permaculture and localhost test

**Comment by albjeremias** [comment]
https://nextjs.org/docs/pages/building-your-application/optimizing/images

https://github.com/helpbuttons/helpbuttons/blob/main/web/src/elements/ImageWrapper/index.tsx#L73

https://github.com/helpbuttons/helpbuttons/blob/main/web/src/elements/ImageWrapper/index.tsx#L95

need to replace with <Image but also needs a defined width/height 100% is not valid.

**Comment by albjeremias** [comment]
request to the api smaller images.. when uploading big images.. and then going to explore the image is big, and should be resized
