### ISSUE TITLE
checkboxes are very confusing

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#281]
@watchoutfreedom 
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/0f422165-6ed7-4ed9-89b8-de91876c955d)

i'd suggest for checkboxes to be more explicit, this black and white are not very clear. 

recommendation:
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/c974ab28-502b-4949-9b32-78dadbb4b93a)

**Comment by watchoutfreedom** [comment]
ok copy will try to think something better
