### ISSUE TITLE
Make configuration menus as side menu instead of accordion

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#287]

**Comment by albjeremias** [comment]
![image](https://github.com/user-attachments/assets/dc0f46d9-96e4-435d-a444-8e6e26c86e4b)

**Comment by albjeremias** [comment]
@watchoutfreedom maybe what we can do in this issue is to have a different more simple form when creating the network, and then a more complex one when changing configuration! what do u think

**Comment by watchoutfreedom** [comment]
I think we can make the same design work with more complex and less complex, but yes, they will be different
