### ISSUE TITLE
problems after signup

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#32]
Can´t signup, after pushing button to sign up the screen goes to blue loading and the error is this:

Captura de Pantalla 2023-02-09 a las 19.18.56

**Comment by watchoutfreedom** [comment]
![1](https://user-images.githubusercontent.com/23015314/217907254-d556a670-fec1-4072-8a79-e2707588ae9c.jpg)

**Comment by watchoutfreedom** [comment]
after taking down docker and up again and reloading it seems to recover the session

**Comment by albjeremias** [comment]
need the log of the api. can you also send a screenshot of the requests in the network tab?
