### ISSUE TITLE
Think about user data structure to be decentralized / federated / shared

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#331]
We need to start thinking about how can the users share the info between networks , and networks federate so the user can easily share, and/or migrate info between networks.

Ideally users have a key phrase that's unique and represent a global profile that can be downloaded and reshared somewhere else, or just when two networks federate one network can access the info in the other, by some kind of protocol. (How this connects to fediverse?)

Any help is welcome, thanks

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/issues/52

**Comment by albjeremias** [comment]
Create or use a network communication protocol so we can share content between networks. We could manage network federation criteria in the Administrator settings, this would consist in:

    Paste Network unique ID to add to federation
    Revert network federation
    Choose if you want to share your new posts with the federated network, or just publish in your network the other network posts.
    Other network's users will be able to register in your network without invitation
    Notification should in that case reflect which network is notifying and jump to that network when clicked.

In HomeInfo and Explore view, touching in the network's name, display a selector dropdown with the info of the federated networks and the networks that the user has already logged in with the same account.
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/6b99dffb-e95f-4003-89c3-a2f622681b61)


https://github.com/helpbuttons/helpbuttons/issues/428

**Comment by watchoutfreedom** [comment]
Can we add this to new features priorities

**Comment by watchoutfreedom** [comment]
treated in other issues https://github.com/helpbuttons/helpbuttons/issues/428
