### ISSUE TITLE
detecting the user location

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#37]
so.. we get the user location.. what do we do with it?
there are 3 ways where we get the localization from:

    default network localization
    writting a place on the "Where to start" in the homeinfo
    getting user localization

So how is the flow of all of this?

> Access to Explore directly shows network's default location. But there are some exception:
-When you type a place in the HomeInfo page andd jump to Expore with that address
-When you type a place in search filter inside Explore page,
-When you are in a already started session, navigating, so the coordinates shown in the map are kept in Store and you keep viewing the same area when you change between pages or go fwd/bckwd
> -User location is an optional feature. That's a Network-related option. There will be three cases for this:
> Center view in user location, (the button will appear in search filters or over the map when enabled in network options).
    Publish button in user location (That's the "Near me" option in the "Where?" menú)
    Update button with user location. That's a more complex and demanding feature. The idea is for the button to change position with creator location. That's useful for on-the-go services and instant help that needs to happen within the closest members of a network.

**Comment by albjeremias** [comment]
it works like this:
- user gives permission to check the location
- location is detected after some seconds...
- if user is in the homeinfo screen it will show up this:
![image](https://user-images.githubusercontent.com/26681446/232014313-f900ca3a-4872-4288-bd39-7c1f8d8817e6.png)

**Comment by watchoutfreedom** [comment]
Better if we get teh location after click
