### ISSUE TITLE
Send login link always says link sent even if error 

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#384]
When you try to login with link, it always says link sent even if there an error or wrong email

**Comment by albjeremias** [comment]
this is a security feature... you could be able to find out all the email accounts registered in the website if it would give an error when fails to send email.

**Comment by albjeremias** [comment]
change alert from success to info

change message to : "Si tienes una cuenta, recibirás un email"

**Comment by albjeremias** [comment]
"newLoginTokenSent": "Si tienes una cuenta, recibirás un email con un link para hacer login.",
    "newLoginTokenSent": "I've you have an account you will receive an email with a link to login.",
