### ISSUE TITLE
when hovering a button highlight hexagon

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#418]

**Comment by watchoutfreedom** [comment]
This has been lost in the last dev

**Comment by watchoutfreedom** [comment]
It breaks when you select an hexagon, deselect, and try to hover again

**Comment by watchoutfreedom** [comment]
yes in macos Chrome and safari. Try selecting an hexagon and then deselecting

**Comment by albjeremias** [comment]
@watchoutfreedom can you test now please? I think there was a problem with the new automatic deployment :)
