### ISSUE TITLE
follow system users, buttons or tags

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#439]
**not sure of the viability of these options but leaving the issue for full comment on it. 

Instead of the follow user approach, implement the support button, user or tag feature. Display a heart icon in the button page that allows you to receive updates in this button in your email. Changes in button data would be notified to the persons that support the buttons or users. 

If user follow a button: (add Heart to boton header)
Receives button updates only posts in the email / activity

If user1 follows an user2: 
User1 receive notification of all buttons created by user2 in the email / activity

If user supports a tag / button type:
User receive notification of all buttons created with the tag chosen in the email / activity

/*receive an alert for every new button created with that tag and button type/s
This would be configured from user config section under profile. Tag field similar to button type form in css. In it you can add tags and select the types to be notified.*/

**Comment by albjeremias** [comment]
- https://github.com/helpbuttons/helpbuttons/issues/156
- https://github.com/helpbuttons/helpbuttons/issues/155

**Comment by albjeremias** [comment]
https://sendgrid.com/pricing/

https://nodemailer.com/usage/bulk-mail/

**Comment by albjeremias** [comment]
follow button / follow tags  / follow location
send resume every 1 day, 1 semana, 1 mes
pick some radius...
  button:
    - post... 
  tag:
    - new button 
  location:
    - new button
