### ISSUE TITLE
add visibility to network private / public

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#44]
![image](https://user-images.githubusercontent.com/26681446/217923372-22f31989-762e-4e31-a874-2da0488e3c62.png)

The button can have 3 different options of privacy:
  - Public 
  - registered local only (visible for all registered users of the current network, but not for public)
  - unlisted (visible for followers only) 

this options should also reflect what is configure on the network basis. on the network there should be a default privacy which is when a user is creating a button.
also the network administrator, should be able to choose, to remove options, like can decide all buttons are public. or that no buttons can be made public.

**Comment by watchoutfreedom** [comment]
I would leave this options strictly to the network creator. If the admin wants all private just for the one that logs, or or public to all the internet. Later we can update specific button behaviour.

**Comment by albjeremias** [comment]
https://stackoverflow.com/a/60608920
