### ISSUE TITLE
Missing avatar in comment notif in ACTIVITY page

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#440]
En las notificaciones de comentarios, el avatar del user que hace el comentario no aparece en la notificacion

**Comment by albjeremias** [comment]
where is this happening? I see avatars of users eveywhere..

**Comment by albjeremias** [comment]
could not replicate. avatar and button image is replaced.. when it doesn't exist... if it exists it seems to work fine.

**Comment by albjeremias** [comment]
closing for now
