### ISSUE TITLE
Show variables when price is 0 

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#488]
Enable a boolean message like "Price to be defined" that can be selected in price option. Show the string "Free" when price is 0.

**Comment by deepgawande** [comment]
Hii I would like to solve this issue.

**Comment by albjeremias** [comment]
@deepgawande can i support you?

**Comment by deepgawande** [comment]
@albjeremias sure

**Comment by deepgawande** [comment]
I am contributing for the first time I appreciate your support
