### ISSUE TITLE
Activity page content

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#497]
ACTIVITY PAGE : 
- Notify my new buttons
- Notify my new post
- Notify my new comment
- Notify public / private comments which reference to me
- notifications of posts of buttons that i follow
- notifications of buttons created in a tag inside a location defined in the profile page

features to add:
- When you comment in a button, automatically add this user to the followers of this button

FILTROS DEL FEED
All activity, My activity, My interests activity

**Comment by albjeremias** [comment]
All activity, 
 My activity, 
 My subscriptions activity, (mensagens privadas e publicos)
