### ISSUE TITLE
generate Creator Update Posts automatically when edited

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#530]
Feat: After editing a field in a helpbutton, add a checkbox that ask 'Notify users of the changes'. If the checkbox is marked, there should be a post generated with the changes in the Feed for it.

If you edit type, title, description, tags, or any other field the post should say:

"Username changed title from 'Example title1' to 'Example title2' "

**Comment by albjeremias** [comment]
extremely complex task.

**Comment by watchoutfreedom** [comment]
Closed for the future
