### ISSUE TITLE
Add most used tags to tags section in Homeinfo

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#541]
Add most used tags in homeinfo page: the 10 most used tags would appear in this section apart from the selected by the administrator. These would be called "Popular topics" and can be disabled in administrator settings

**Comment by albjeremias** [comment]
`select tag,count(tag) from (select unnest(tags) as tag from button) as tags group by tag;`

**Comment by albjeremias** [comment]
@watchoutfreedom 
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/7183c133-7860-410c-8ca8-62f66863fcdf)

should we remove the selection of tags on the network configuration?

**Comment by albjeremias** [comment]
add top tags under tags of network
