### ISSUE TITLE
warn that event is hidden 

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#559]
- send email, requesting to edit event date

**Comment by albjeremias** [comment]
@watchoutfreedom i change this.. when the button is updated last time (with a post or a comment, ) < 3months ago, nothing happens. maybe we have to think better this limits.. 

events:
AND "eventEnd" < now() - INTERVAL '3 days'
AND "updated_at" < now() - INTERVAL '3 months' 

buttons which dont have an event has a custom field:
AND "updated_at" < now() - INTERVAL '3 months'

**Comment by watchoutfreedom** [comment]
That seems logic. I seems that events ended 3 days ago are not disappearing in networks.

**Comment by albjeremias** [comment]
> That seems logic. I seems that events ended 3 days ago are not disappearing in networks.

i dont understand what do you mean with this?

**Comment by watchoutfreedom** [comment]
Nervermind. The ideal behaviour would be to have the events disappear right after their last day

**Comment by albjeremias** [comment]
so what you want is to change from 3 days to 1 day?

issue that was dealing with this before:
https://github.com/helpbuttons/helpbuttons/issues/508
