### ISSUE TITLE
Add select interest field in signup

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#561]
Add optional tag selection field in the SIgnup form. User could select topics and types of helpbuttons that want to be notified about.

The default tags would be the hb types, the most used tags and the network tags. The behaviour would be selct/deslect each element with the touch.

**Comment by watchoutfreedom** [comment]
![Captura de Pantalla 2024-02-05 a las 17 03 57](https://github.com/helpbuttons/helpbuttons/assets/23015314/6469f07a-d8a8-4790-8d36-ec7ad9e2d347)

**Comment by albjeremias** [comment]
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/758f54d2-8dbb-4751-a549-8516f820ce41)
finish css for signup choosing interests
