### ISSUE TITLE
subscribe to button types

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#563]
- add button types as an interest to follow for users (similiar to following interests)

**Comment by watchoutfreedom** [comment]
DESIRED BEHAVIOUR: 
Use the type name as a tag, if the user suscribes to a tag that is the same as the type name, then all the buttons of that type will be included as notifications in the mail

**Comment by albjeremias** [comment]
> DESIRED BEHAVIOUR: Use the type name as a tag, if the user suscribes to a tag that is the same as the type name, then all the buttons of that type will be included as notifications in the mail

can i simply add a tag to which button with the name of the button type?

**Comment by watchoutfreedom** [comment]
Ok let's keep it like that for now
