### ISSUE TITLE
horizontal scroll is not accessible for mobile users

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#570]
on the explore view, the horizontal scroll of the cards is not easily understood for mobile users

**Comment by watchoutfreedom** [comment]
I'm getting this issued and improved with smaller cards

**Comment by watchoutfreedom** [comment]
Already on the last pull request ready to check @albjeremias  on mobile

**Comment by albjeremias** [comment]
@watchoutfreedom now its a
