### ISSUE TITLE
set activites not clickable when button is deleted

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#577]

**Comment by albjeremias** [comment]
very complicated issue.. needs deep reimplementation of activities

**Comment by albjeremias** [comment]
give an api different response.. and say "button" has been finalized

**Comment by albjeremias** [comment]
buttons are not deleted anymore, they are set as expired (when passed more than 3 months without activity or the event end is past)

**Comment by albjeremias** [comment]
please retest deleting a button and open from activity

**Comment by watchoutfreedom** [comment]
Now not found error page displays but back button goes to explore instead to actuvity

**Comment by albjeremias** [comment]
to make it clear.. if a button is set as expired, it is possible to click it.. but if the button is "finalized" doesn't make sense to make it clickable... what can be done is to add a button on the activity saying: "restore button" but still i dont think that it is a good idea. i think the user should just create a new button
