### ISSUE TITLE
periodic date, fix structure and css

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#608]
![Captura de Pantalla 2024-03-04 a las 20 39 01](https://github.com/helpbuttons/helpbuttons/assets/23015314/f1f74c3f-35b9-47d4-a0d1-a614fe4aea9f)

Days would need to go first in this case, and then choose the stranting and end date

**Comment by albjeremias** [comment]
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/a01900a4-7b91-498c-a711-0d8a8bfd01fa)

need help with selected weekdays! @watchoutfreedom

**Comment by watchoutfreedom** [comment]
pending css but working
