### ISSUE TITLE
Enable the only list mode in network settings

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#609]
Study and enable an option with no map:

- Results will be displayed in list full height by default, filtered by search field
- No filters will display de default network area results. 
- Place and radius search will display that area

**Comment by albjeremias** [comment]
You mean that the admin can choose not to have a map forever? are you sure this is useful? isn't it better maybe to store this on the localstorage ? so that the browser stores the behavior.. maybe there could be a default one to show.. but should the other ones be hidden?

**Comment by watchoutfreedom** [comment]
Let's keep this just as "default display mode" for now. Admin can choose if the default explore view in mobile is List, Map or both

**Comment by watchoutfreedom** [comment]
Repeated in other issue
