### ISSUE TITLE
  allow network configuration to select a default display mode (display only list by default)

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#620]
Enable Map / List default and exclusive display modes in network configuration.
-Display only map (Only for pin map option not hexagon)
-Display Only List

Think about a plan for enabling the rest of the options for the locations modules:
- Anywhere (shows just in list view)
- From one place to another (A special button type module)
- Follow me in real time (A special follow the user module)

**Comment by watchoutfreedom** [comment]
Better explained, after the last weeks this issue changed.

- allow network configuration to select a default display mode (display only list by default)

- lets move location options to another issue

**Comment by albjeremias** [comment]
sorry lets make it clear is this only affecting the mobile version?
how does it affect on the desktop version?

is the map available on the list mode? or the user can use the buttons to show it?

**Comment by watchoutfreedom** [comment]
This only affects mobile version but I'm sendind this to future milestone
