### ISSUE TITLE
Use the parapraph div in the notifications

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#629]
PROBLEM
We aren't using the title and parapgraph sections properly in notification component

SOLUTION
Use the title and paragraph sections, the title for who and where and the paragraph for the content

![Captura de Pantalla 2024-03-12 a las 13 46 42](https://github.com/helpbuttons/helpbuttons/assets/23015314/c672dd25-8b02-41ae-a954-897823d01307)

![Captura de Pantalla 2024-03-12 a las 13 47 18](https://github.com/helpbuttons/helpbuttons/assets/23015314/2b615af9-2f65-4ed2-ac51-f5d23ead640c)

**Comment by albjeremias** [comment]
'activities.newbutton' 
    "newbutton": "A new _helpbutton_ was published '{0}' in '{1}'",

'activities.deletebutton'
    missing message... not showing on activities

'activities.newpost'
    "newpost": "There is a new post '{0}' in the _helpbutton_ '{1}' by '{2}'",

  
'activities.newcomment'
    "newcomment": "'{2}' commented '{0}' answer to the post '{1}'",

'activities.newfollowing'
    "newfollowing": "your are now following the _helpbutton_ '{0}'",

**Comment by watchoutfreedom** [comment]
'activities.newbutton'
image: Button image or user avatar
title:  Button title
text: A new helpbutton was published in 'Location', press this card to visit,

'activities.deletebutton'
image: Button image or user avatar
title:  'Button title' was deleted

'activities.newpost'
image: Useravatar
title:  New post in 'Button title' by '{2}'
"text": "Post content',

'activities.newcomment'
image: Useravatar
title:  'username' replyed in 'Button title'
"text": "Comment content',

'activities.newfollowing'
"title": "You now follow the 'buttontype'",
"text": "buttonName',

'activities.newfollowed'
"title": "Username now follows your 'buttontype'",
"text": "buttonName',

**Comment by watchoutfreedom** [comment]
Some misplacements in the fields, see the the images:

![Captura de Pantalla 2024-03-19 a las 12 01 11](https://github.com/helpbuttons/helpbuttons/assets/23015314/c79fa42c-8c57-4e16-b61c-ec5fbd0c3745)
![Captura de Pantalla 2024-03-19 a las 12 06 01](https://github.com/helpbuttons/helpbuttons/assets/23015314/477b1fe4-31b5-40a8-9b8a-b7fe7d62ca07)


-The title needs ":" at the end, and the

'activities.newpost'
image: Useravatar
title: 'Username' published an update in 'Button title':
"text": "Post content',

**Comment by watchoutfreedom** [comment]
'activities.newbutton'
image: Button image or user avatar
title: Button title
text: Your _helpbutton_ was published in 'Location', press this card to visit.

**Comment by albjeremias** [comment]
> Some misplacements in the fields, see the the images:
> 
> ![Captura de Pantalla 2024-03-19 a las 12 01 11](https://private-user-images.githubusercontent.com/23015314/314027161-c79fa42c-8c57-4e16-b61c-ec5fbd0c3745.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTM1NDcsIm5iZiI6MTcxMDg1MzI0NywicGF0aCI6Ii8yMzAxNTMxNC8zMTQwMjcxNjEtYzc5ZmE0MmMtOGM1Ny00ZTE2LWI2MWMtZWM1ZmJkMGMzNzQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzMDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NTI2YjRmZGIyYjBjYzRkNmUzZWNkM2M3YTk2M2U5ZDZiYzRiY2M3ZTU5MmIxOGFiMjA4ZjQ0NmVmOTRmMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bs6EC-eJGrKMJqHHes4-WWBFgu1qBxrKgVJbovJAzUs) ![Captura de Pantalla 2024-03-19 a las 12 06 01](https://private-user-images.githubusercontent.com/23015314/314028234-477b1fe4-31b5-40a8-9b8a-b7fe7d62ca07.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTM1NDcsIm5iZiI6MTcxMDg1MzI0NywicGF0aCI6Ii8yMzAxNTMxNC8zMTQwMjgyMzQtNDc3YjFmZTQtMzFiNS00MGE4LTliOGEtYjdmZTdkNjJjYTA3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzMDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhOTMxN2I2YTM2NjlkNTJkZGI4YzZjYTZiMjYzNGYzZTQ2MTg1NWRiOGMxMmIwMTBlNTExZjg5OGYzNGU2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhKQpNPBd85M32rnX8vzpCMrA9o9fIHPl-d2b3p6lrY)
> 
> -The title needs ":" at the end, and the
> 
> let's make it simpler:
> 
> 'activities.newpost' image: Useravatar title: 'Username' posted in 'Button title': "text": "Post content',

thats because its missing spanish translations

"newpost": "New post in '{0}' by @{1}",
"newbutton": "A new helpbutton was published in '{0}', press this card to visit",
"newcomment": "'{0}' replied in '{1}'",
 "newfollowing": "your are now following the '{0}'",
    "newfollowed": "{0} now follows your '{1}'",
    "myhelpbuttons": "My _helpbuttons_",
    "deletebutton": "{0} was deleted"

**Comment by watchoutfreedom** [comment]
pending spanish will complete
