### ISSUE TITLE
Filter by date finalize passed events

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#630]
PROBLEM
In the list filter order, if you choose order by date of event Event are ordered from the newest but including the ones that passed

SOLUTION
Show first the ones that are happening closer to date but hide the ones that passed, finalize them after they end if needed

**Comment by albjeremias** [comment]
i think this are related: https://github.com/helpbuttons/helpbuttons/issues/559

maybe what you mean is a cronjob automatically finalizing events after the date passed? or after 3 days after the event end date?

**Comment by watchoutfreedom** [comment]
yes they're related. It's better to hide events right after the date yes. later we can figure out what we do with finalized events Thanks

**Comment by albjeremias** [comment]
so what you want is to change from 3 days to 1 day?

issue that was dealing with this before:
https://github.com/helpbuttons/helpbuttons/issues/508

**Comment by watchoutfreedom** [comment]
Yes, when the day of the event is over, process to finalize it so it doesn't display in the results. We can work on what to do with these finalized later (ideally users could see them finalized int heir accounts)

**Comment by watchoutfreedom** [comment]
![Captura de Pantalla 2024-04-01 a las 14 25 53](https://github.com/helpbuttons/helpbuttons/assets/23015314/fc3f982a-879c-4745-9fe0-9a818e1e63f8)

**Comment by watchoutfreedom** [comment]
aqui
