### ISSUE TITLE
Allow color selection even when not selected in top

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#636]
PROBLEM
I f you don't press the exact color in the color picker it doen't accept the selection. Users usually are not familiarize with the color picker and don't know they need to push on the upper color rectangle.

DESIRED
Allow picked color if not selected and assign black by default

**Comment by albjeremias** [comment]
I dont understand what you want. i think this needs redesign

**Comment by watchoutfreedom** [comment]
Yes it needs design work, What I say is to set a default black color if the color picker is not set

**Comment by albjeremias** [comment]
change to main color as default
