### ISSUE TITLE
Missing loading when upload big image

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#646]
PROBLEM
Button New form stays frozen when the users selects a big image for the button after publish button is pressed.

SOLUTION
Add a loader in the publish button so the user knows it's processing

**Comment by albjeremias** [comment]
yes this makes sense. need some ux hints on how-to do this. how do you want it to look like?

**Comment by albjeremias** [comment]
only set submit as loading... disable all inputs
