### ISSUE TITLE
New Button Templates

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#657]
PROBLEM
Some cool features could be achieved by allowing extra locations in the button forms / template. 

PROPOSED
If we had a field in the JSON with a array of locations, we could create routes and paths that would be useful for:
Transport sharing
Sharing Natural paths, hiking
Delivery

**Comment by watchoutfreedom** [comment]
@albjeremias Changed this issue for discussion about new Button Templates and when can we have them:

- Allow area location for buttons 
- Allow start - end point location 
- Add a catalog option, where several "products", with name, description, image and price can be added

**Comment by albjeremias** [comment]
this is like 3 or more different issues. this is too big to be in a milestone

**Comment by watchoutfreedom** [comment]
Yes this is just for discussion. We can start with the catalog module in this milestone

**Comment by watchoutfreedom** [comment]
addressed in others
