### ISSUE TITLE
create default support button

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#659]
PROBLEM
In the HomeInfo page, when you click in an administrator contact link. They link to first button created in the app by the first admin.

PROPOSED
Enhance admins to add their phone and/or contact button in the homeInfo and profile page. Remove the default logic of the main/first button as the default contact.

Show a message saying, "You're admin , add a phone or helpbutton of contact so people can reach you" in the home info

![Captura de Pantalla 2024-04-05 a las 11 26 26](https://github.com/helpbuttons/helpbuttons/assets/23015314/c6d69a31-fc2d-4975-96a5-5aa8a2cc264d)

**Comment by watchoutfreedom** [comment]
@albjeremias what's missing here? We need to add a message encouraging the admins to create a contact button. 
Maybe it makes sense for creator admin to go directly to button creation right after network creation, so it creates a contact button.

**Comment by albjeremias** [comment]
> @albjeremias what's missing here? We need to add a message encouraging the admins to create a contact button. And the contact helpbuttons would need to exist for that. As summary:
> 
> -We need to have a alert message in home and admin profile to tell the admin that he doesn't have a contact helpbutton enabled / created.
> 
> -Contact button won't be the first button of the app, ideally every admin can create an assistance helpbutton that is independant.
> 
> Also there's a bug in admin section, when you're admin and you visit your own profile, you cannot access your contact button. 

Instead of this complicated way, can we create a button automatically when the network is created... and all admins can edit this button? It just makes things way easier.

**Comment by watchoutfreedom** [comment]
OK let's create one by default

**Comment by albjeremias** [comment]
> OK let's create one by default

there will be an option on the network configuration to create this button, or to update(edit) it!

This button will be editable by all admins only. basically it will be a button of type support, which will have as its location the center of the network. and the admin won't be able to select a type, it will be "support" type.

@watchoutfreedom what do u think?
