### ISSUE TITLE
Remove the auto mention from the replies in the comments

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#663]
PROBLEM
When someone replies to a comment the @name keep staying so they acumulate till infinite.

PROPOSED
Remove the @name if it's to the same user that is writting the message

**Comment by albjeremias** [comment]
> PROBLEM When someone replies to a comment the @name keep staying so they acumulate till infinite.
> 
> PROPOSED Remove the @name if it's to the same user that is writting the message

im confused, how does it happen it accumulates till infinite? can you explain better.
im also confused because, how can a user reply to itself?

**Comment by watchoutfreedom** [comment]
Example:

PersonA replyes to update:
@personB hello!

PersonB replyes:

@personA @personB Hello! how are you?

PersonA replies again:

@personB @personA @personß I'm fine I need something

**Comment by watchoutfreedom** [comment]
That is what's happening now, so the names start to acumulate

**Comment by albjeremias** [comment]
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/7fac6084-989a-4867-ab92-32e9697afdb3)
can't replicate.

**Comment by watchoutfreedom** [comment]
Yes there's no loop but the second Message has the same name as the person that is replying
