### ISSUE TITLE
Add a admin user call in homeinfo 

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#664]
PROBLEM
Many users that are not familiarized with new tech need help to create content and intereact. 

PROPOSED
Add a float popup in the homeinfo page with the  question  'Do you need help publishing? Call an admin' and the icon of the phone. ' This is just if the admin has the phone calls enabled.

**Comment by albjeremias** [comment]
please make a drawing first :) also i dont really like this idea. I made this issue 
https://github.com/helpbuttons/helpbuttons/issues/673 we can discuss both.

**Comment by watchoutfreedom** [comment]
1. pending to link data to the ui design made.

2. Would add this as optional in the configuration menu

**Comment by albjeremias** [comment]
> 1. pending to link data to the ui design made.
> 
>     2. Would add this as optional in the configuration menu

![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/8c18ebee-dd13-4e4b-b6c2-ea192bf24364)


So the first icon is to make a call if the admin setup a phone number.
The second, will open a mailto
I dont understand the third icon.

**Comment by watchoutfreedom** [comment]
first : call phone
second go to contact button
third go to whatsapp
