### ISSUE TITLE
 In Networks Config menu , Show location over button when it's selected

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#665]
PROBLEM
In networks configuration menu, you don't see the networks location selected outside of the field once the map is closed.

PROPOSED
Use a similar model to ButtonNew location field. Adding, a location over the button.

**Comment by albjeremias** [comment]
Do you mean the address? on the network you should not setup an address, should you? it should be an area

**Comment by watchoutfreedom** [comment]
@albjeremias yes I mean a hint about the selected area, either we add an approximate central spot or we show the map i the form
