### ISSUE TITLE
admin assistance to guide users to register on hb

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#666]
PROBLEM
People not familiarized with new technologies struggle to create profiles, have emails and publish on these platforms.

PROPOSED
Enable a register option without phone, the user can add the phone but it need to wait for an admin to call it in order to activate the users account. 

1. AN user registers adding a phone in the signup field. The register field displays a message 'Use email or phone number. If using a phone number, you'll need to wait for an admin to confirm your signup'. 
2. Admins receive an email saying users that tryed to register with phone.
3. Admin call these users to help them to enter and use the app

**Comment by albjeremias** [comment]
maybe it could work like this:
 - on the signup page, there should be a link to another page which says: "Enter your phone number" _______ 
 - admin receives the email with the phone number to call, and a link to register a new user with this phone number already set.
 - admin call the phone number and requests details of the user.

questions:
 - how will the user login?
 - this works very easily on a mobile app, not a app on the browser.
 - should be very transparent the conditions of giving away the phone number. people could use helpbuttons to abuse. we need to certify helpbuttons networks somehow?

**Comment by watchoutfreedom** [comment]
I would do for now:

Under the email field in signup "I don't have email"

Let's keep this as an exception for non email users. I would move this to Then the admin contact section appears: 
"Contact administrator for login without email"
Call, message, etc

Admin assist the person with phone or username.

User completes signup with his phone/username as credential. Admin can reset the password in case the user forgets.

In this case, we need a dialog where the admin can reset a given phone/username password so the user can re-enter
