### ISSUE TITLE
add helpbuttons info on what the project is, in homeinfo

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#673]
do you think this could be cool? people keep on asking me what is this... 
maybe for now, cause we are starting could be just after the jumbo!
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/38cde49a-0829-45f3-880e-1b02c2f9a10e)

**Comment by watchoutfreedom** [comment]
I think we can explain it at the bottom of the page, in the top is not relevant for the majority of the users. We can add recomendations about the networks description
