### ISSUE TITLE
Images are broken in Buttonfile

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#674]
Image don't display in dev branch inside Buttonfile

**Comment by albjeremias** [comment]
Do you have any error on the browser console? or on the terminal? can you please give more info.

**Comment by watchoutfreedom** [comment]
https://dev.helpbuttons.org/es/Explore?zoom=6&lat=36.9325&lng=-5.9184&btn=nEyVVvrV3rWfoyJ6TkUW5dqyYV3zMVV7Ec2R

![image](https://github.com/helpbuttons/helpbuttons/assets/23015314/1697d8eb-c890-47a6-9118-0308ab16c11b)

**Comment by albjeremias** [comment]
I don't understand. I don't see any error on that button. it seems to me that is just a button without uploaded images. just tested to create a new button with an image and works fine.
