### ISSUE TITLE
Empty error randomly appear when visiting buttonfile

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#687]
![Captura de Pantalla 2024-04-23 a las 15 10 51](https://github.com/helpbuttons/helpbuttons/assets/23015314/450c80c5-1088-41ab-bbc2-7ecbd160a41f)
![Captura de Pantalla 2024-04-23 a las 15 11 05](https://github.com/helpbuttons/helpbuttons/assets/23015314/2c01c3cc-d63a-4778-bcb8-56e4a2901773)

**Comment by watchoutfreedom** [comment]
Appear when trying to find the Updates.
![Uploading Captura de Pantalla 2024-04-23 a las 15.58.21.jpg…]()

**Comment by albjeremias** [comment]
i have no idea how to replicate this. can you please tell me a step by step how do you get there?

**Comment by watchoutfreedom** [comment]
Will try in the future. Cant replicate totally

**Comment by watchoutfreedom** [comment]
Lets try to test and see
