### ISSUE TITLE
Network tags doesnt display

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#689]
In homeinfo, network tags are not displaying properly . Some used tags are missing and expired buttons tags are counted.

**Comment by albjeremias** [comment]
> In homeinfo, network tags are not displaying properly . Some used tags are missing and expired buttons tags are counted.

Which ones are missing do you have any idea? Should the tags of expired buttons disappear? I need more info ... can you show me an example of a missing tag?

**Comment by watchoutfreedom** [comment]
We should hide expired or finalized buttons tags. In future versions we should make a better tag display that allows explanations about the tags.

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/commit/263ee23939a5ae300ec0cc40cbe9bc8fe3414fd6
