### ISSUE TITLE
Feat - Secure way of maintaining the logged status

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#690]
It would be easier for users if they could keep the session logged with a direct link to the app in their phone desktop / launch screen. Is there a secure way of keeping the session logged from in the same device, maybe if the user marks the device as safe?

**Comment by albjeremias** [comment]
> It would be easier for users if they could keep the session logged with a direct link to the app in their phone desktop / launch screen. Is there a secure way of keeping the session logged from in the same device, maybe if the user marks the device as safe?

we can't do much on our side. do u known why are the users losing their logged session?

**Comment by watchoutfreedom** [comment]
When you minimize the navigator tab or window, the session expires and you need to login again. Which criteria is being used for closing the the logged session now?

**Comment by albjeremias** [comment]
> When you minimize the navigator tab or window, the session expires and you need to login again. Which criteria is being used for closing the the logged session now?

this doesnt happen on my phone. the session is never closed only if your browser clears the cookie
