### ISSUE TITLE
improvements on ui

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#693]
- more transparent hexagons different button types
- remake configuration form
- on maxZoom add hexagon with more transparency
- Emojis

**Comment by watchoutfreedom** [comment]
@albjeremias I can't add transparency to the hexagon on max zoom cause the hexagon disappears.

**Comment by albjeremias** [comment]
> @albjeremias I can't add transparency to the hexagon on max zoom cause the hexagon disappears.

you requested to make the hexagon disappear... i made now a commit on dev to make it appear again on maxZoom.

https://github.com/helpbuttons/helpbuttons/commit/099ada29de5c25430e7fef8e54eced340e01de0a
