### ISSUE TITLE
test all mail notifications

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#696]
list all mails send.. and test one by one that they are working:
 - sendDailyUserOutbox
 - NewPostComment
 - RenewButton
 - expired button
 - activation mail
 - login token
 - 

notifications:
 - 
 
add

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/wiki/Notifications-on-activity-and-email

@watchoutfreedom can you check this out, please? :)

**Comment by watchoutfreedom** [comment]
Yes that's ok
