### ISSUE TITLE
send notification when button expires.. and when button is renewd

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#699]
activity doesnt have any notification about expiration and buttons renewals

**Comment by watchoutfreedom** [comment]
We need to change the approach on this issue @albjeremias  will try to summarize in another issue. But we need to allow expiration settings to be selected in the type.

**Comment by albjeremias** [comment]
> We need to change the approach on this issue @albjeremias will try to summarize in another issue. But we need to allow expiration settings to be selected in the type.

please dont create more issues. just do it here. thanks
