### ISSUE TITLE
Own profile visit and navigatios throws 404

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#705]
Not sure the reason. Sometimes when navigating in the profile menu, entering in the different sections like "edit network" goes to a 404 not found

[Nest] 12119  - 05/04/2024, 2:28:28 PM     LOG [HTTP] GET /networks/findById 200 1787B - node ::1
[Nest] 12119  - 05/04/2024, 2:28:31 PM     LOG [HTTP] GET /post/findByButtonId/7Y9tq3ectxdGLR9ion-k3tCN8bR6hEOqj1Hu 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:28:31 PM     LOG [HTTP] GET /post/findByButtonId/7Y9tq3ectxdGLR9ion-k3tCN8bR6hEOqj1Hu 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:28:40 PM     LOG [HTTP] GET /activity/find 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:28:53 PM     LOG [HTTP] GET /buttons/findAdminButton 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:28:56 PM     LOG [HTTP] GET /users/whoami 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:28:56 PM     LOG [HTTP] GET /users/whoami 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:28:56 PM     LOG [HTTP] GET /networks/config 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:28:56 PM     LOG [HTTP] GET /networks/findById 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:29:00 PM     LOG [HTTP] GET /buttons/findAdminButton 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1
[Nest] 12119  - 05/04/2024, 2:29:16 PM     LOG [HTTP] GET /activity/find 304 0B - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 ::1

![Captura de Pantalla 2024-05-04 a las 14 31 18](https://github.com/helpbuttons/helpbuttons/assets/23015314/cc32a760-cdfe-461b-8c36-40f266280709)

**Comment by watchoutfreedom** [comment]
Visit own profile contact button throws sometimes the same error

**Comment by albjeremias** [comment]
I have no idea how-to replicate this... can you please explain better step by step how I can replicate this error? thanks

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/commit/0136e65875e451ae14576a20cae8bbcd0505e003
