### ISSUE TITLE
Bug when entering the homeinfo page

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#706]
![Captura de Pantalla 2024-05-05 a las 8 17 56](https://github.com/helpbuttons/helpbuttons/assets/23015314/4cfe9ac5-bd09-4980-a773-2e43e94724da)

**Comment by albjeremias** [comment]
@watchoutfreedom can you please explain to me how this happens to you? it won't happen to me.

**Comment by albjeremias** [comment]
probably is fixed on refator-activity branch..
