### ISSUE TITLE
show "network is private" error when guest users tries to see content of private network

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#71]
Copy button link and pasting it in another tab or browser doesn't work as a link to the button. Throws this error: 
![Captura de Pantalla 2023-02-26 a las 17 08 58](https://user-images.githubusercontent.com/23015314/221422322-128826a2-5b05-4ec7-8c6e-1a5af7351942.jpg)

**Comment by albjeremias** [comment]
do you have it as a private network? maybe we need a window of "this network is private" ill do that!

**Comment by watchoutfreedom** [comment]
Probably should not be a private error since I'm logged. But yes, ideally it shows a message with the answer

**Comment by watchoutfreedom** [comment]
Also this was in the host if that helps

**Comment by watchoutfreedom** [comment]
YEp, just logged and clicked copy link, then went to another tab. 
![Captura de Pantalla 2023-02-27 a las 16 18 26](https://user-images.githubusercontent.com/23015314/221603696-6cac5c6f-e2a7-47d0-aa04-33ffd476e09d.jpg)

**Comment by albjeremias** [comment]
testing steps:
 - set network as private
 - share link to button

**Comment by albjeremias** [comment]
for this issue, would be cool to first test how is this working, and to group here all bugs related on creating a private network

**Comment by watchoutfreedom** [comment]
@albjeremias Made some test. Starting a discussion about this:

1. PRIVATE NERWORK
- Present: Private network/Invite/QR login lost the functionality. Invitations where removed in the past and QR only invites form fields seems to not react to interaction. 

- Expected: There are three privacy states for a network: **Private** (Invitation-Only sign up, Only logged can publish and can search/see), **Semiprivate** (Invitation-Only sign up, Only logged can publish, everyone can search/see helpbuttons), **Public** (Anyone can register, anyone can publish, everyone can search /see) 

-  QR login is a separate property that can be activated in admin console. New QRInvites can be generated just by the admins. Regular link invitations can be generated/send by anyone.

2. MODERATION:

-Present: Helpbuttons moderation list form checkbox doesn't seem to react to interaction. 

-Expected: As a separate property, networks admin  could activate a moderation list where all helpbuttons posted by users need to be approved by admins.

**Comment by watchoutfreedom** [comment]
@albjeremias updated definitions here. Lmk what u think to make mockups

**Comment by albjeremias** [comment]
All networks are **public**!

**endorsed can publish without moderation always**
 - moderated or not moderated

**signups allowed:** 
 - anyone can register
 - can be invited by any user
 - can only be invited by endorsed users
 - can only be invited by admins

Allow users to register with a code as a anonymous. (this checkbox only shows if "anyone can register")

**Comment by watchoutfreedom** [comment]
@albjeremias on invitation-only registration options, share section in homeinfo would need to change. I'll make layout. 

<img width="1320" height="690" alt="Image" src="https://github.com/user-attachments/assets/777e428f-6b91-4820-bc62-e9556aca312b" />

**Comment by albjeremias** [comment]
<img width="758" height="524" alt="Image" src="https://github.com/user-attachments/assets/901a00ec-3ff2-48e6-b705-d714e48d6ace" />

Moderation of network: 
  - all buttons before published need to be approved by admin, except from endorsed users
  - all buttons are published without waiting approval

signups:
 - anyone can register
 - required invitation by other user
     - inviteOnly: true, make sure users cant register in other ways.
 - only endorsed users can send invitations
    - inviteOnlyByEndorsed: the same as before.. but check if user has been endorsed 
 - only admins can send invitations
    - inviteOnlyByAdmin: the same as before.. but check if user is admin

Allow users to register with code as anonymous. (checkbox only shows if "anyone can register")

**Comment by albjeremias** [comment]
related: https://github.com/helpbuttons/helpbuttons/issues/1461

**Comment by albjeremias** [comment]
DONE -> Moderation of network: 

signups:

DONE    anyone can register

DONE    required invitation by other user

    only endorsed users can send invitations
       - limit creating invitations to endorsed users!

    only admins can send invitations
       - limit creating invitations to admins!

DONE -> Allow users to register with code as anonymous. (checkbox only shows if "anyone can register")

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/commit/2316d8e4207c6b692a9b82af9e80d76e3adb01b3

done. needs testing
