### ISSUE TITLE
show error field when map is not selected

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#717]
After creating a network and add all the data, tryed to go to edit network configuration and the form was empty and an error like this appeared :

Validation errors {"statusCode":400,"success":false,"message":"validation-error","validationErrors":{"exploreSettings":["exploreSettings should not be empty"]}}

**Comment by albjeremias** [comment]
there should be an error on the "Choose location" field, isn't there?

**Comment by watchoutfreedom** [comment]
It was a deeper bug I think but I can't reproduced. The entire form cleared alone.
