### ISSUE TITLE
Problem checking uncompleted fields in Profile and Network config

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#719]
PROBLEM
There's no alert when there are uncompleted or wrong fields in profile edit or network config and the accordions are closed

PROPOSED

Add an alert and a message under the submit button to let the user know that there are uncompleted fields

**Comment by albjeremias** [comment]
formslist: 
 - new post
 - new comment
 - new button
 - edit button
 - signup
 - configure network
 - new network
 - edit profile
