### ISSUE TITLE
Add button type and color to cards

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#72]
Link button type color and name to cards both in map, list and buttonFile. ie in this case the button is need type and would be red but the card shows green
![Captura de Pantalla 2023-02-26 a las 17 19 50](https://user-images.githubusercontent.com/23015314/221422746-be03de83-d19c-4a83-ba5c-4f0baa7395b1.jpg)

**Comment by albjeremias** [comment]
also fix card 
![image](https://user-images.githubusercontent.com/26681446/228856763-0fd631a9-3c4b-4ab2-9180-24e68ff46468.png)

**Comment by albjeremias** [comment]
moved to #40
