### ISSUE TITLE
Search by distance, leave distance search as optional

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#723]
Search by place and search by distance are a bit confusing for the user. Add explanation on the field and keep search by distance hidden and unactive as optional (by default search in all the network)

When reloading the search filters, the searched place is hidden, show it more evidently so it can be removed/updated

Keep the order search as relevant

**Comment by albjeremias** [comment]
> Keep the order search as relevant

what do you mean with order "search as relevant"?


> Search by place and search by distance are a bit confusing for the user. Add explanation on the field and keep search by distance hidden and unactive as optional (by default search in all the network)

can you draw something in penpot? or explain better how you imagine it.. can i use an accordion? or something like that? 

> When reloading the search filters, the searched place is hidden, show it more evidently so it can be removed/updated

I will split this into another issue. https://github.com/helpbuttons/helpbuttons/issues/727
