### ISSUE TITLE
Explorer Back button doesn't work in mobile - android

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#726]
History stores different map states so back button doesn't work properly in explore page

**Comment by albjeremias** [comment]
> History stores different map states so back button doesn't work properly in explore page

can you explain better.. like where you click what happens.. what is wrong and how it should be? or a video? or screenshots. thanks

**Comment by watchoutfreedom** [comment]
the problem is when you are on the map and you use the back button of the phone. ie. You come from homeinfo, change the map a few times, then the back button of the phone doesnt work beacuse all the map positions are in phone navigator cache

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/tree/goback-currentBtn

there is some big issues on doing this... 

1- window state is pushing more states than needed, when going back url is hiccupping 
2- added a custom hook to detect when backbutton is clicked so that the explore is updated.

**Comment by watchoutfreedom** [comment]
ok checked, this was a proposal from user testing so let's try this and in future user tests lets see how people react
