### ISSUE TITLE
improve chosen location to filter on the advanced filters ui

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#727]
improve this:
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/43576bc7-a34f-4124-b498-2d371eaf16b6)

how it is in buttonNew 
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/eba0888c-a41c-44f9-ad65-b3a2959b7563)

**Comment by albjeremias** [comment]
done in here: https://github.com/helpbuttons/helpbuttons/pull/728

**Comment by watchoutfreedom** [comment]
Made some changes on the branch that need to be completed with some missing logic in buttons of the advancedfilters forms @albjeremias

**Comment by albjeremias** [comment]
> Made some changes on the branch that need to be completed with some missing logic in buttons of the advancedfilters forms @albjeremias

which branch?
