### ISSUE TITLE
where? hidden in Buttonnew view

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#73]
The input where? appears hidden in ButtonNew form at the beggining. It appears after you add an image. 
![Captura de Pantalla 2023-02-26 a las 17 22 08](https://user-images.githubusercontent.com/23015314/221422911-80f27a30-7b00-48c4-87ba-ff3c59118011.jpg)

**Comment by albjeremias** [comment]
change the behavior.. set it up as "disabled" until the user sets an avatar and a name?! 

if user tries to submit show errors below the location field saying "Please setup an avatar and a name, before picking a place in the map?"

**Comment by watchoutfreedom** [comment]
Ok I understand, yes it´s bettter to see it from the beggining
