### ISSUE TITLE
Too many hexes error

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#732]
PROBLEM
Explore view
When exploring the map in min zoom, and there are no helpbuttons in view, the map stays loading without resolving. That also happens sometimes after creating a button and the error shows *too many hexes*

SOLUTION
A possible solution for this future errors is to add the message "move the view if not loading content", if no results, move the map for more info. But better would to remove the loader

**Comment by albjeremias** [comment]
can't replicate any of this. can you be more specific on how this happens?
