### ISSUE TITLE
Erase account option

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#733]
Add an option to erase account inside the profile edit

Ask for confirmation in a picker

**Comment by albjeremias** [comment]
this will delete:
  - user profile
  - all the buttons
  - all the posts
  - all the comments
  - all activity
  - delete all pictures:
    - need add user to uploads table.. !

**Comment by watchoutfreedom** [comment]
Move delete option to profile edit instead, also back button after confirm message it's broken, lets make it an alert with no closing time
