### ISSUE TITLE
when creating button, location should be private on frontend

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#737]
if use chooses to hide address, the frontend should send the center of the hexagon, not the place of the marker... 
also improve the location picker to show the address

**Comment by albjeremias** [comment]
@watchoutfreedom can you test the location selector in the button? maybe i can also use this ui/ux to the network location, giving the option to don't restrict zone, restrict zone (where the hexagon appears)

**Comment by watchoutfreedom** [comment]
That looks great for the button, for the network the ideal state would be to select hexagons and then have the restrict option that you mention, but for now I think is ok with the zoom to limits strategy.

**Comment by watchoutfreedom** [comment]
Closing with this for a future issue @albjeremias
