### ISSUE TITLE
Gap in the list view due to number of post loaded

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#741]
Load more even number of post by page in the list desktop view so there's no empty space . The empty space makes you think there're no more posts
![Captura de Pantalla 2024-06-05 a las 20 04 12](https://github.com/helpbuttons/helpbuttons/assets/23015314/e3170510-23d0-449e-b0be-2969dc148c8b)

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/commit/b18df25d7abc40b9aa8675a316ef6eb2adf16bb8
