### ISSUE TITLE
feat: Message publishing under captcha + IP

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#743]
I'm looking for easy ways to interact with the app since lots of users I know from the countryside aren't that familiar with technology. We have added the direct admin contact in the Home page but it would be good to enhance autonomous interaction. 

The aim of this app is not to store user data or use it in any sense, sstorage is just a provisional service it can povide while the people contact to cooperate in real life, so it makes no sense for us to ask every user to register. 

We should look for alternative ways to verify posted content, like captcha, IPs or even phone without having an external sms service. 

Let's say we keep the phone of the person as an internal code, we don't send verification sms, just store the code as his/her phone and if that person enters the data again we know it's the same person. 

We check it's not a bot with a captcha protection, and we keep track of the user with the phone / email used for posting. (we can still keep the email verification, not the sms)

If the user that posted with a phone uses it too many times, we ask an admin to check it that's a right usage. 

In that way we allow people that doesn't have an email to post, and we also don't need to pay external services to check if the usage is ok.

**Comment by albjeremias** [comment]
> I'm looking for easy ways to interact with the app since lots of users I know from the countryside aren't that familiar with technology. We have added the direct admin contact in the Home page but it would be good to enhance autonomous interaction.
> 
> The aim of this app is not to store user data or use it in any sense, sstorage is just a provisional service it can povide while the people contact to cooperate in real life, so it makes no sense for us to ask every user to register.
> 
> We should look for alternative ways to verify posted content, like captcha, IPs or even phone without having an external sms service.
> 
> Let's say we keep the phone of the person as an internal code, we don't send verification sms, just store the code as his/her phone and if that person enters the data again we know it's the same person.
> 

How do we verify that that phone number belongs to that person? You can't automatically get the phone number of a person, its manually written by the user

> We check it's not a bot with a captcha protection, and we keep track of the user with the phone / email used for posting. (we can still keep the email verification, not the sms)
> 

I feel like captcha protection might be a harder thing for people on the country side. but hopefuly im wrong

> If the user that posted with a phone uses it too many times, we ask an admin to check it that's a right usage.
> 
> In that way we allow people that doesn't have an email to post, and we also don't need to contract external services to check if the usage is ok.

I proposed to you something like gancio does. which is, users can post stuff anonymously, but they don't get published automatically, the admin needs to approve. if the user has an account, then the stuff is published automatically

**Comment by watchoutfreedom** [comment]
Thinkin further, this should be someting optional depending on the network, but it seems a better system for small networks in rural areas or networks intended for older population specially.

**Comment by watchoutfreedom** [comment]
> > I'm looking for easy ways to interact with the app since lots of users I know from the countryside aren't that familiar with technology. We have added the direct admin contact in the Home page but it would be good to enhance autonomous interaction.
> > The aim of this app is not to store user data or use it in any sense, sstorage is just a provisional service it can povide while the people contact to cooperate in real life, so it makes no sense for us to ask every user to register.
> > We should look for alternative ways to verify posted content, like captcha, IPs or even phone without having an external sms service.
> > Let's say we keep the phone of the person as an internal code, we don't send verification sms, just store the code as his/her phone and if that person enters the data again we know it's the same person.
> 
> How do we verify that that phone number belongs to that person? You can't automatically get the phone number of a person, its manually written by the user
> 
> > We check it's not a bot with a captcha protection, and we keep track of the user with the phone / email used for posting. (we can still keep the email verification, not the sms)
> 
> I feel like captcha protection might be a harder thing for people on the country side. but hopefuly im wrong
> 
> > If the user that posted with a phone uses it too many times, we ask an admin to check it that's a right usage.
> > In that way we allow people that doesn't have an email to post, and we also don't need to contract external services to check if the usage is ok.
> 
> I proposed to you something like gancio does. which is, users can post stuff anonymously, but they don't get published automatically, the admin needs to approve. if the user has an account, then the stuff is published automatically

That's ok too, we can ask admins to be proactive in moderation

**Comment by watchoutfreedom** [comment]
not needed for now, the one that is working with qr is ok, and just send buttons to moderation if it's published anonimously
