### ISSUE TITLE
Latest activity widget in Homeinfo

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#744]
I'm thinking about the possibility of having a lastest activity widget in homeInfo. With the geenral activity of the network, the lastest helpbuttons published and the lastest messages. Maybe that helps to know what's happening in a better way. 

That widget may be also needed internally , in the admin console, but with all the public and private data together. 

![Captura de Pantalla 2024-06-12 a las 12 46 14](https://github.com/helpbuttons/helpbuttons/assets/23015314/e7ff87fe-267d-458b-8c77-ceb5aca205fa)

**Comment by watchoutfreedom** [comment]
This Lastest activity widget may include:

-Latest Helpbuttons posted,
-Latest public comments posted

**Comment by albjeremias** [comment]
> This Lastest activity widget may include:
> 
> -Latest Helpbuttons posted, -Latest public comments posted

I think you mean:
 - helpbuttons created
 - latest posts created in buttons
 - latest public comments

**Comment by watchoutfreedom** [comment]
> > This Lastest activity widget may include:
> > -Latest Helpbuttons posted, -Latest public comments posted
> 
> I think you mean:
> 
> * helpbuttons created
> * latest posts created in buttons
> * latest public comments

Yes!

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/pull/774
