### ISSUE TITLE
Load initial number of list posts depending on height

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#758]
Add a function that tracks the device height and adjust the number of initial helpbuttons loaded depending on it. We need to adjust number depending on the total height of the screen / card height . If the screen is medium or large width the number would be in pairs. If it's mobile is just one card per row. 

![Captura de Pantalla 2024-06-18 a las 10 58 49](https://github.com/helpbuttons/helpbuttons/assets/23015314/8422d11f-c9d2-455a-957e-ac67d937dd1b)

**Comment by albjeremias** [comment]
when screens height is too big, the scroll stops working. need function to calculate number of loaded buttons if screen height is too big
