### ISSUE TITLE
Translations doesn't work on explore when logged

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#762]
When logged, select a dif language than english, set as profile language, go back to explore Explore and shows english instead of the selected language.

**Comment by albjeremias** [comment]
can't replicate. do you do this on the dev? what is the default language of the network? what language did the user had?

**Comment by watchoutfreedom** [comment]
Tte default language in rey network is spanish, the default of the user is spanish but when logged shows english and helpbutto s word doesnt change

**Comment by albjeremias** [comment]
i cant replicate in dev.helpbuttons.org what is "rey" network? can u explain me how-to replicate this?
