### ISSUE TITLE
Show phone issues

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#768]
Show owner phone on helpbutton page to the owner too. Phone does not show if owner is number is entered with spaces in the form. 

SOLUTION

REMOVE SPACES OR SHOW A MESSAGE ERROR TO CHANGE PHONE BY THE USER

**Comment by albjeremias** [comment]
from what I understand. 
you say that the phone won't show to the owner? 
Also if the phone number has spaces it won't show?

**Comment by watchoutfreedom** [comment]
Phone still doesnt show in helpbuttons if it was entered with an space in the form field

**Comment by albjeremias** [comment]
hook stopped working. :s now it should be done
