### ISSUE TITLE
When uploading several images from the phone, the app freezes

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#770]
If you select to upload three images taken with the phone the app stays loading till infinity. 

Solution: show an upload aprox time count or check if theres a problem and show the message

**Comment by albjeremias** [comment]
now it shows this. how should it be?
![image](https://github.com/helpbuttons/helpbuttons/assets/26681446/ce80d83c-60c2-4e3a-a6c8-c66ac0ad9cef)

**Comment by watchoutfreedom** [comment]
Maybe indicate progress or steps ?

**Comment by watchoutfreedom** [comment]
@hirunatan could you help us?? Thank you very much
