### ISSUE TITLE
Simplify publishing vol 2

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#773]
After the discussions we had in the past, here's a proposal:

If the user is not logged, add a form to register inside the ButtonNew page and the Publish comment Component.

this form may include a captcha, and won't have username field, the username would generate from the Name field. I would have interests field

If user has an account, there will be a small link with the 'I have an account' option, so it will follow the path that we already have.

ADVANTAGES: We can erase the Register section from the navbar after making this option. Also all the back-forth of routes that we haVE for publishing and that lead to many errors and uneasy ussage will disappear-

PHONE OPTION: This would be something the network creator can update in the network options: If user uses a phone in the register form, the system sends a message to all admins to approve the publication. The form will show a message warning the user about the use of phone number only excepcionally and it will need to wait (one approval is enough)

**Comment by watchoutfreedom** [comment]
Edit: Instead of adding the form inside of buttonNew, make the signup and login a popup and remove the need of routes

**Comment by watchoutfreedom** [comment]
The idea is to keep the flow like this : 

Fill form helbutton/comment ---> fill contact data to register / login ----> publish

**Comment by albjeremias** [comment]
on publish form of button:
 - on top add register fields: just email and name 
 - or login option
 - on bottom change to "register and publish"

**Comment by watchoutfreedom** [comment]
New thoughts about this:

When we have the QR functionality, enable an "anonimous publishing" thru a QR code and display this options on top of the form

**Comment by watchoutfreedom** [comment]
![Captura de Pantalla 2024-07-02 a las 11 12 01](https://github.com/helpbuttons/helpbuttons/assets/23015314/fa2abef5-dd38-474f-8038-3a6aed74095c)

**Comment by watchoutfreedom** [comment]
![Captura de Pantalla 2024-07-02 a las 10 28 39](https://github.com/user-attachments/assets/f7f54755-328c-4618-af10-2f29e4b6fd39)

**Comment by watchoutfreedom** [comment]
@albjeremias  Just include the form i added after the comment section, or on top of the button creation form.

The QR form for publishing anonimously would be included in the register page too as an option.

**Comment by albjeremias** [comment]
split into 2 issues:
https://github.com/helpbuttons/helpbuttons/issues/820
https://github.com/helpbuttons/helpbuttons/issues/819
