### ISSUE TITLE
request login link throws error the first time you try, second works

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#775]
it seem login link thrwos error the first time you try, both in destop and mobile. Second workd. The message is this:

![Captura de Pantalla 2024-06-26 a las 16 19 34](https://github.com/helpbuttons/helpbuttons/assets/23015314/406f2469-e450-4db8-a38e-01a05ff73cec)

**Comment by albjeremias** [comment]
when the dev is being updated, because something was pushed into github dev branch, the backend might fail. thats what happened.
