### ISSUE TITLE
Disclaimer and Accept conditions link under Register Button

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#793]
So we don't have problems with the law, there should be a link to privacy terms in the register forms

- Disclaimer saying 'We don't use cookies banner'
- Explanation on what the cookies are in the faqs section
- Message 'I accept the publishing conditions' under comment send and helpbutton  publish

**Comment by albjeremias** [comment]
need to known where to link for the terms and conditions.. 
is a link to here: https://dev.helpbuttons.org/Faqs enough ? it's not clear that this are the terms and conditions.

also we need to add a banner or something warning the website uses cookies, and if people don't want to use cookies, we need to implement a version without cookies (for guest users only)

**Comment by albjeremias** [comment]
on mastodon you need to accept the the rules of the server and the privacy policy:
![image](https://github.com/user-attachments/assets/fe9d4665-ea05-4be8-b7a2-9d6c4381a759)

![image](https://github.com/user-attachments/assets/4728e473-bf39-4b31-a489-8affb0897f6d)
https://mastodon.social/privacy-policy

**Comment by watchoutfreedom** [comment]
I would keep it simpler for now. Just a note under the signup field

**Comment by albjeremias** [comment]
continuation https://github.com/helpbuttons/helpbuttons/issues/813
