### ISSUE TITLE
Display suggestions under filters tag search field

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#794]
Display suggestions under the text field based on:

- based on the most used tags of the network
- Once text entered, display suggestions based on the text entered

![Captura de Pantalla 2024-07-02 a las 8 24 11](https://github.com/helpbuttons/helpbuttons/assets/23015314/22d0af07-39d7-4406-b806-227217a66839)

**Comment by albjeremias** [comment]
- advanced fields should have 5 tags suggestions, which changes has you write. when u add a tag it will show up with an X so you can remove it 

- button form : same as above!

- signup 30 tags instead of 5

**Comment by watchoutfreedom** [comment]
@albjeremias let's make one follow tag button for all, instead of replicate the follow button for each new tag.

**Comment by albjeremias** [comment]
@watchoutfreedom it should follow all the tags at the same time? :thinking: or maybe the button should be smaller?

**Comment by albjeremias** [comment]
> @albjeremias let's make one follow tag button for all, instead of replicate the follow button for each new tag.

https://github.com/helpbuttons/helpbuttons/commit/9b65ddabc4fd6af31c72de40503bc3bfafe3de4b
