### ISSUE TITLE
Add "Install app" button on Homeinfo

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#802]
Detect an display and UI alert , if the user has no webapp installed. So it can be installed
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Trigger_install_prompt

**Comment by watchoutfreedom** [comment]
After first install, then erase the app. install buttons never appears again

**Comment by albjeremias** [comment]
im not sure about this .. the commit was this one:
https://github.com/helpbuttons/helpbuttons/commit/bb26c25d69d4291c96906debf11b4fbd7a3fbb9b

**Comment by albjeremias** [comment]
and this experimental "standard" is not working on safari.! 

![image](https://github.com/user-attachments/assets/2e28adc2-0a69-4838-8cde-f1126be9102a)
https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent#browser_compatibility
