### ISSUE TITLE
webapp installation issues with safari/iphone

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#803]
Evaluate what it will take to display push notifications with a webapp

**Comment by albjeremias** [comment]
need to review why on iphone won't work. probably forgot to request permission at the correct moment

**Comment by albjeremias** [comment]
i activated this again in https://dev.helpbuttons.org 
can you please test if it works on iphone? @watchoutfreedom

**Comment by watchoutfreedom** [comment]
can't test on dev, there's a critical error in homeinfo

**Comment by watchoutfreedom** [comment]
it doesnt work on ios yet

**Comment by watchoutfreedom** [comment]
the app cannot be installed when there's another instance of thelpbuttons in the phone. Also allow notification has no effect and no error appears on console

**Comment by albjeremias** [comment]
i have android, and cant replicate. i have dev and redana installed.
