### ISSUE TITLE
Location adjusment and features discussion

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#804]
Process map info so users know better where they are. Some times village names dont appear

**Comment by watchoutfreedom** [comment]
Users not familiar with maps usually get lost when managing map location

**Comment by albjeremias** [comment]
what do you mean with this? the tiles that show from open street maps?

**Comment by albjeremias** [comment]
"The map renderings available at OpenStreetMap.org use pre-rendered raster images. That is, the server uses pre-determined rules to decide what to display at each zoom level and then generates static image files that are shown to you. Since these are static images, there isn't a way to show a different thing for each user, or have fancy actions like mouseover for map features. There's work under way to make a dynamic rendering (similar to the way Google Maps works), but that's still a work in progress."

https://help.openstreetmap.org/answer_link/82043/

**Comment by watchoutfreedom** [comment]
![Captura de Pantalla 2024-07-10 a las 11 22 13](https://github.com/helpbuttons/helpbuttons/assets/23015314/cdb57d20-6605-45d2-9c8d-b58322d6e655)

maybe thsi is for the future but users find this, and they don't know where they are

**Comment by watchoutfreedom** [comment]
No names, no references, we need to think about it

**Comment by watchoutfreedom** [comment]
@albjeremias what about this? allow admin to create one button type that is just for them, is like a PIN or key spot on the map. it will appear like this:
![Captura de Pantalla 2024-07-11 a las 12 28 23](https://github.com/helpbuttons/helpbuttons/assets/23015314/d793e84d-100a-410e-8fa1-b0056de30daa)

**Comment by watchoutfreedom** [comment]
in this way we can help users to know where they are

**Comment by albjeremias** [comment]
I'd recommend the users to go to Open Street Maps and contribute :)

**Comment by watchoutfreedom** [comment]
Well that's for the ones that know what they are doing, but this is a feature so the ones that doesn't understand maps very well don't get lost

**Comment by albjeremias** [comment]
> Well that's for the ones that know what they are doing, but this is a feature so the ones that doesn't understand maps very well don't get lost

maybe there are more detailed geojson which we can try to render in top of the map... it's not a trivial task.

**Comment by watchoutfreedom** [comment]
The best is for admins to have a special type of pin that they can add, but yes if u have a better alternative tell me

**Comment by albjeremias** [comment]
sorry, my mistake, i have a question. so you mean in the network configurationthere will be a new collapsable, which will will allow admins to add cities?

or we can create a "special" kinda of button for admins, which only appears for admins with a name and coordinates. (on the backend it wont be a button will be a "place") all places will have same color and same size? Or maybe we can find a database with all this places? where can we find opendata about spain villages?

**Comment by albjeremias** [comment]
I have a better idea... why won't a user when adding a button, clicks a place on the map.. it gets the address, if the user doesn't like the address, can keep the coordinates and edit the address... and this addresses will keep on being added as soon as users add them once, so when the user searches for this address again the coordinates are already there. is this what maybe u want? @watchoutfreedom

**Comment by watchoutfreedom** [comment]
> I have a better idea... why won't a user when adding a button, clicks a place on the map.. it gets the address, if the user doesn't like the address, can keep the coordinates and edit the address... and this addresses will keep on being added as soon as users add them once, so when the user searches for this address again the coordinates are already there. is this what maybe u want? @watchoutfreedom 

This is a great idea, but different what I proposed . What I commented is for showing bigger key place names when the zoom is out, cause sometimes map doesn't show desired key areas names till the zoom is big and the users get lost. But I would keep both, your idea and mine. @albjeremias

**Comment by albjeremias** [comment]
related: https://github.com/helpbuttons/helpbuttons/issues/798

**Comment by watchoutfreedom** [comment]
is this implemented? Can we add a better map for monday?

**Comment by albjeremias** [comment]
> is this implemented? Can we add a better map for monday?

no

**Comment by watchoutfreedom** [comment]
Changed title so:

- Users can add key location / places to the network list if they don't find in the results
- Admins can add Key places pins in the maps with name so they're seen all the time.
- We make more test to find the best way to limit the places results according to network needs (limit by network location area?)
- Maybe limit map bound to that locations¿

**Comment by albjeremias** [comment]
related https://github.com/helpbuttons/helpbuttons/issues/844

**Comment by albjeremias** [comment]
so i think there should be a list of places with respective address and coordinates... and the admin can set them to show on the map

**Comment by watchoutfreedom** [comment]
Yes it makes sense.

**Comment by watchoutfreedom** [comment]
Completing the feature, connected to this issue:
https://github.com/helpbuttons/helpbuttons/issues/971


The key places that the admin can add, appear:

 On the side menu on homeinfo commented in this issue https://github.com/helpbuttons/helpbuttons/issues/971
 
 Also under the location field, in SearchFilters component
![Captura de Pantalla 2024-11-28 a las 11 06 46](https://github.com/user-attachments/assets/9d9a44f2-a227-423d-903d-dc4d1d982a45)

**Comment by watchoutfreedom** [comment]
closing this, and refering in the main locations issue
