### ISSUE TITLE
activity duplicated on homeinfo - rebuild notification system=

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#806]
Home user activity only shows duplicated user info when publishing a button

**Comment by albjeremias** [comment]
duplicated activities on homeinfo

**Comment by albjeremias** [comment]
rethinking activity....

 https://blog.devgenius.io/notification-system-design-that-scales-361e03b1d9e0

https://medium.com/wrike-design/how-to-design-a-notification-system-step-by-step-manual-with-examples-b4263fb20c03

https://tannguyenit95.medium.com/designing-a-notification-system-1da83ca971bc
Edited12:10 AM

**Comment by albjeremias** [comment]
also affects this https://github.com/helpbuttons/helpbuttons/issues/792

**Comment by albjeremias** [comment]
- if button is for approval, do not publish activity.
 - when button is approved, add new activity
 - when is for approval, notify admins?
 - homeinfo: new post, new button
 - do not post activity of first post in the buttons
 -
