### ISSUE TITLE
Add Alert when adding new button type

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#807]
After pressing create new btn type in the network form, nothing displays, neither errors or success, so user doesn't exacly know what happens

**Comment by albjeremias** [comment]
the button is not added automatically, its only when you save the configuration.

what is true is that the form should be cleared... and maybe should scroll a bit up so the admin sees the new type

**Comment by watchoutfreedom** [comment]
Yes maybe scroll up
