### ISSUE TITLE
network config seo

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#808]
Network config  ( and user config?) page SEO  is not showing network name

**Comment by albjeremias** [comment]
why do you want SEO for this pages? makes no sense.

**Comment by watchoutfreedom** [comment]
Beca

**Comment by albjeremias** [comment]
that's only the page title, because SEO needs pre-rendering from the server and its a bit more complicated. anyway i can't replicate this on current dev.
