### ISSUE TITLE
make activity window, with list of created buttons, posts made, comentarios, 

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#82]
[ ] new.button
[ ] new.button.post
[ ] new.button.post.comment
[ ] ? be able to follow tags, follow other users.. timeline... uff later.

**Comment by albjeremias** [comment]
![image](https://user-images.githubusercontent.com/26681446/232172909-2c944752-a5e7-4149-a7ca-ef43e2af0dc8.png)
https://github.com/helpbuttons/helpbuttons/commit/2ed83c030ecafc290075d02575dba81db4c325c5

**Comment by watchoutfreedom** [comment]
[ ] new.button
[ ] new.button.post 
[ ] new.button.post.comment
[ ] new.button.post (in the button you commented)
[ ] new.button.post.comment ( In the post you commented )

**Comment by albjeremias** [comment]
this is done. now we need to notify more people besides the owner of the button. i wonder who :) probably we will need something similiar to github? where you can follow like a button?

**Comment by watchoutfreedom** [comment]
It should be notified every comment in a thread you commented and every owner update in a thread you commented. At least I think it can work for now. Later we can add the like function maybe...?

**Comment by watchoutfreedom** [comment]
is this done?

**Comment by albjeremias** [comment]
> is this done?

i dont remmember anymore, need to test
