### ISSUE TITLE
create embedable widget

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#845]
Work on a n easy solution to copy and insert Helpbuttons list / map in other websites. 

Discuss what's needed and next steps.

**Comment by albjeremias** [comment]
![image](https://github.com/user-attachments/assets/334198bb-cdf4-4f50-bf88-a3575f5e3927)

**Comment by albjeremias** [comment]
https://social.coletivos.org/@ajeremias/113093885604947734

**Comment by watchoutfreedom** [comment]
pending popup component to be included
