### ISSUE TITLE
Erase latest activities related to buttons

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#846]
Once a helpbutton is deleted, latest activities related to it should disappear. 

If difficult, display a not found cause deleted or similar . 

Now the app displays an error fetching

**Comment by albjeremias** [comment]
I disagree, i think that's how it should work. can you explain me exactly how you imagine it? I can delete all activity.. but then the user looses track that it created and deleted a button... i don't see any problem to have a broken link to a deleted button, i think it makes the app more transparent and clear for the enduser.

**Comment by albjeremias** [comment]
when u finalize a button now, it will delete all posts and all comments on that button from the homeinfo activity

**Comment by albjeremias** [comment]
deleting from homeinfo

**Comment by watchoutfreedom** [comment]
still shows in local 
![Captura de Pantalla 2024-09-25 a las 23 39 51](https://github.com/user-attachments/assets/5c5eefa4-2f0f-47d5-aa49-dba1672605f3)

**Comment by albjeremias** [comment]
continues here: https://github.com/helpbuttons/helpbuttons/issues/850
