### ISSUE TITLE
Submitting helpbutton owner update  to a helpbutton doesn't reset images

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#854]
Image stays in the field under the form after submitting
![Captura de Pantalla 2024-09-26 a las 0 29 54](https://github.com/user-attachments/assets/683dfadd-ea41-40bd-adfd-e032dbaa170b)

**Comment by albjeremias** [comment]
@watchoutfreedom can you confirm this please?
