### ISSUE TITLE
error in desktop and mobile, when generating the invitations pdf

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#856]
It seems that pdf generator has some problems with the mobile display. We could limit it to desktop. 

![Captura de Pantalla 2024-09-26 a las 2 43 07](https://github.com/user-attachments/assets/7ec31ace-4070-46a6-8f1a-0c33409e40ab)

**Comment by albjeremias** [comment]
which browser? which mobile? works for me

**Comment by watchoutfreedom** [comment]
At least safari , chrome , brave on ios renders the pdf without download options visible
