### ISSUE TITLE
suggest tags

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#86]
- [ ] use react-select
- [ ] also linkify all tags.. maybe jump to explore?! with tagged buttons filtered

**Comment by watchoutfreedom** [comment]
suggestions would be best based on description and/or title of the button. Also they could appear depending on the writting. But we can leave this for now since we are going to search in filters also in titles and descriptions.

**Comment by albjeremias** [comment]
#38 duplicate
