### ISSUE TITLE
hide buttonTemplate and all buttons, instead of deleting!

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#860]
has css issues

![image](https://github.com/user-attachments/assets/5c544d85-ccf3-4584-b773-fe325188c69a)

**Comment by watchoutfreedom** [comment]
@albjeremias updated the css

**Comment by watchoutfreedom** [comment]
In order to simplify the form, we should allow deleting the initial buttons or moving them to a bin
