### ISSUE TITLE
Area Activity tab on Explore

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#88]
Have an explore section that shows on list recent activity on the area. Similar to activity tab but centered on positioned network activity instead of personal.

**Comment by albjeremias** [comment]
https://github.com/helpbuttons/helpbuttons/commit/2ed83c030ecafc290075d02575dba81db4c325c5

![image](https://user-images.githubusercontent.com/26681446/232172839-4c2a4701-c54d-4159-a22d-b98d24e94d2a.png)
