### ISSUE TITLE
Map issues

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#93]
- [ ] change to selfhost, so no need for an api key from opencage
  -> https://about.maps.earth/
  
- [ ] implement clustering
 -> https://github.com/uber/h3-js

![image](https://user-images.githubusercontent.com/26681446/227633650-3b560585-dab8-47a4-b0ac-48e94d0a1b40.png)

**Comment by albjeremias** [comment]
list of map tile providers

https://switch2osm.org/providers/

**Comment by watchoutfreedom** [comment]
hexagon modular model 
https://github.com/Adriamelendo/Honeycomb-Map

**Comment by albjeremias** [comment]
@hirunatan we have some questions regarding the map.
You can test the last version in:

https://dev.helpbuttons.org/Explore 

normally its synced with the dev branch!

questions:
- is it possible to selfhost tiles? Do you known any cool project?
- is it possible to selfhost routing? in this app [organic maps](https://github.com/organicmaps/organicmaps) they deal with offline map, maybe a solution based on this would work? 
- what about hexagons for clustering, do you have some examples? Or some explaining of implementations of this? would be great, till now i found this library [h3-js](https://github.com/uber/h3-js) which i believe could be a good start  to integrate with [pigeon-maps](https://pigeon-maps.js.org/)

**Comment by albjeremias** [comment]
- HoneyComb maps? clustering, privacy [utube](https://www.youtube.com/watch?v=Pgekw-15vSI&ab_channel=Adri%C3%A0Melendo) [code](https://github.com/Adriamelendo/Honeycomb-Map/blob/master/frontend/scripts/convert-regions.js)
-

**Comment by hirunatan** [comment]
Yes! This is the project I worked for, to have hexagonal maps. Unfortunately we didn't finish the packaging and documentation step, so you will need to examine the source code to see how does it work.

But the prototype is working, and the result is awesome, it would be possibly a game changer if you include this in HelpButtons.

About tile hosting, I cant't help you very much. I know more or less how does it work, but never did it myself.

**Comment by albjeremias** [comment]
> Yes! This is the project I worked for, to have hexagonal maps. Unfortunately we didn't finish the packaging and documentation step, so you will need to examine the source code to see how does it work.
> 
> But the prototype is working, and the result is awesome, it would be possibly a game changer if you include this in HelpButtons.
> 
> About tile hosting, I cant't help you very much. I know more or less how does it work, but never did it myself.


https://h3geo.org/
