### ISSUE TITLE
When empty area due to hidden location, show message

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#931]
When the map zoom to area where hidden buttons are place, show alert: "Exact location protected"

**Comment by albjeremias** [comment]
![image](https://github.com/user-attachments/assets/59e0fbe4-6f43-4e05-b01f-e61026c37d05)

**Comment by watchoutfreedom** [comment]
Error in setzoom onmap 
![Captura de Pantalla 2024-12-02 a las 18 01 21](https://github.com/user-attachments/assets/d4c55402-5c2b-4c09-a33b-2d70e9f506b5)

**Comment by albjeremias** [comment]
> Error in setzoom onmap ![Captura de Pantalla 2024-12-02 a las 18 01 21](https://private-user-images.githubusercontent.com/23015314/391617861-d4c55402-5c2b-4c09-a33b-2d70e9f506b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTUzOTQsIm5iZiI6MTczMzM1NTA5NCwicGF0aCI6Ii8yMzAxNTMxNC8zOTE2MTc4NjEtZDRjNTU0MDItNWMyYi00YzA5LWEzM2ItMmQ3MGU5ZjUwNmI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIzMzEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Zjc1NWQzZDNjZGQ5NGE4Yzg4MDMzZmY0MGMxY2U0YjQzNjUzOGFiNDBlNDNjZWMyODRhODlmMjExMzM3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XCLV-dIPE2ffYydzVT7JUNGtAQhJ2Tj2NuqBf9HOS0s)

when this happened to you? can you explain me all the stetps please? @watchoutfreedom of fill a new issue? thanks
