### ISSUE TITLE
[BUG] cant read network name

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#960]
### cant read network name

I can't read the name of the network on desktop 1440x900 if the name is too big

---

### 🔍 Steps to Reproduce

1. Go to '/HomeInfo'
2. change your resolution to 1440x900

---

### 🤔 Expected Behavior

 - maybe expands on hovering ?

---

### 📋 Screenshots or Logs

![image](https://github.com/user-attachments/assets/7db988b6-c80d-42c3-94cf-7ebd72d8d946)

**Comment by watchoutfreedom** [comment]
Can't do anything if network name is long, closing, would recommend shot names
