### ISSUE TITLE
[FEATURE] Add proper cookies message

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#963]
Add a floating message in any no logged page "We don't use cookies for no logged users. Visit our cookie policy here. If you log you accept our policy." 

---

.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implement a floating message about cookie policy for non-logged users in the _app.tsx file. The message will be shown on all pages when the user is not logged in.

You can review changes in this commit: https://github.com/lkilu6456546/helpbuttons-helpbuttons-963/commit/d8dd986d7ed04ae23797d6b28415760ce285e728.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by albjeremias** [comment]
> Hello, I tried to solve the issue.
> 
> This is what I did:
> 
> Implement a floating message about cookie policy for non-logged users in the _app.tsx file. The message will be shown on all pages when the user is not logged in.
> 
> You can review changes in this commit: [lkilu6456546@d8dd986](https://github.com/lkilu6456546/helpbuttons-helpbuttons-963/commit/d8dd986d7ed04ae23797d6b28415760ce285e728).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

can you please use our t function for translations? and add translations in common.json. thanks

**Comment by watchoutfreedom** [comment]
yes, example at the "cookies" branch

**Comment by watchoutfreedom** [comment]
@albjeremias is this Pending change cookies message to alert flow?, also we're going to remove the help banner from homeinfo for now.

**Comment by watchoutfreedom** [comment]
If you can help us to integrate the cookies message inside the Alert component that'd be great, thanks
