### ISSUE TITLE
[BUG] share options are not working correctly

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/helpbuttons#964]
### 🐞 Describe the Bug

The share app menu in homeinfo is broken. 

The pdf and invitation creation option are unavailable, click on them just show iframe option.

The app breaks after closing the share menu. 

---

### 🔍 Steps to Reproduce

1. Go to homeinfo page
2. Click share app 
3. Scroll down to share menu and select generate pdf or invitations. Close menu 
4. See errorrs
.

**Comment by tasbi03** [comment]
hey , can you assign me this?

**Comment by albjeremias** [comment]
> hey , can you assign me this?

sure. its a big issue, but can guide you somehow. i'd recommend you first try one of this:
https://github.com/helpbuttons/helpbuttons/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by watchoutfreedom** [comment]
Now it displays a 

backend error: "need-registered" [403] 
console.error @ client.js:2

When opening the share menu and try to create an iframe

**Comment by watchoutfreedom** [comment]
looks solved
