### ISSUE TITLE
[BUG] bulletin gives an error in production

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#976]
### 🐞

when going to generate a bulletin of the buttons, i get a server error!

---

### 🔍 Steps to Reproduce
1. go to share options (on homeinfo)
2. select bulletin generate

---

### 🤔 Expected Behavior

i expect a pdf to be generated

**Comment by albjeremias** [comment]
needs loading, also the invitations generator

**Comment by watchoutfreedom** [comment]
looks solved
