### ISSUE TITLE
[QUESTION] Problem trying to run the project in local

### ISSUE THREAD

**Issue by aitorjs** [helpbuttons/helpbuttons#990]
### 🤔 What's your question?
I want to run the project locally on a linux mint.

I follow the README until I go to http://localhost:3000 and the API container (helpbuttons-api-1) gives the following error:

```bash
 error getting config http://09bca717c2b0:3001/networks/config
helpbuttons-web-1    | TypeError: fetch failed
helpbuttons-web-1    |     at Object.fetch (/app/node_modules/next/dist/compiled/undici/index.js:1:26669)
helpbuttons-web-1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
helpbuttons-web-1    |     at async Function.general (/app/.next/server/chunks/7913.js:50:31)
helpbuttons-web-1    |     at async setMetadata (/app/.next/server/chunks/7913.js:174:76) {
helpbuttons-web-1    |   cause: Error: getaddrinfo EAI_AGAIN 09bca717c2b0
helpbuttons-web-1    |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
helpbuttons-web-1    |     errno: -3001,
helpbuttons-web-1    |     code: 'EAI_AGAIN',
helpbuttons-web-1    |     syscall: 'getaddrinfo',
helpbuttons-web-1    |     hostname: '09bca717c2b0'
helpbuttons-web-1    |   }
helpbuttons-web-1    | }
helpbuttons-web-1    | Failed to proxy http://api:3001//networks/config Error: getaddrinfo EAI_AGAIN api
helpbuttons-web-1    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
helpbuttons-web-1    |   errno: -3001,
helpbuttons-web-1    |   code: 'EAI_AGAIN',
helpbuttons-web-1    |   syscall: 'getaddrinfo',
helpbuttons-web-1    |   hostname: 'api'
helpbuttons-web-1    | }
```
So, it can't find the API at http://api:3001. How can I fix this?

---

### 📋 Context or Background

- ```sudo docker ps```

```bash


$ sudo docker ps
CONTAINER ID   IMAGE COMMAND                  CREATED         STATUS PORTS                                       NAMES
f1a378ecba51   helpbuttons/helpbuttons-web:main "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes 0.0.0.0:3000->3000/tcp, :::3000->3000/tcp helpbuttons-web-1
dcf700821ca6   helpbuttons/helpbuttons-api:main "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes helpbuttons-api-1
fcf7705241f0   helpbuttons/helpbuttons-psql:main "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes (healthy) helpbuttons-db-1
82f3e9389768   redis:7-alpine "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes (healthy) helpbuttons-redis-1
```

- .env content

```
POSTGRES_HOSTNAME=db
POSTGRES_DB=hb-db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=changeme
POSTGRES_PORT=5432
hostName=example.com
smtpHost=
smtpPort=
smtpUser=
smtpPass=
from=
jwtSecret=rf3zFYY5xZpxQo4zHHaKrNV9gNfN3AEo_qN6
REDIS_HOST=redis
REDIS_PORT=6379
VERSION=main
WEB_URL=http://localhost:3000
API_URL=http://api:3001
```

**Comment by Pepe-pep** [comment]
Hi aitor , thank you testing, if you're considering to contribute, I recommend you use the yarn dev both for web and api folder  (make sure you're in those folder when you execute) cheers

**Comment by aitorjs** [comment]
Thank you @Pepe-pep  for the last reply.

I'm considering to contribute.

What you recomend me is:
    - stop helpbuttons-web-1 and helpbuttons-api-1 while helpbuttons-db-1 and helpbuttons-redis-1 are up.
    - go to api folder and run yarn dev to up the api
    - go to web folder and run yarn dev to up the api

¿this is what you recomend me to run help buttons for development?

Thanks!

**Comment by albjeremias** [comment]
> Thank you @Pepe-pep for the last reply.
> 
> I'm considering to contribute.
> 
> What you recomend me is: - stop helpbuttons-web-1 and helpbuttons-api-1 while helpbuttons-db-1 and helpbuttons-redis-1 are up. - go to api folder and run yarn dev to up the backend - go to web folder and run yarn dev to up the frontend
> 
> ¿this is what you recomend me to run help buttons for development?
> 
> Thanks!

can i ask to you please do it from scratch, using [CONTRIBUTING.md](https://github.com/helpbuttons/helpbuttons/blob/main/CONTRIBUTING.md) instead of using the README.md and please mention which step you got stuck!

**Comment by aitorjs** [comment]
Running on development mode following CONTRIBUTING.md :)

Next step. Select an issue from [good first issue](https://github.com/helpbuttons/helpbuttons/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). _Issue recormendations are so welcome!_ ;)

**Comment by albjeremias** [comment]
this one is cool cause you get in contact mostly with the api, and the event emitter! 
https://docs.nestjs.com/techniques/events
i can guide you trough it if you choose it, just comment on it! :)
https://github.com/helpbuttons/helpbuttons/issues/954


https://github.com/helpbuttons/helpbuttons/issues/965

https://github.com/helpbuttons/helpbuttons/issues/895

https://github.com/helpbuttons/helpbuttons/issues/798

pick one! :)

**Comment by aitorjs** [comment]
Thanks @albjeremias for the guidance!
I pick the #895.
I'll start by looking at how the backend is done. I've never worked with nestjs.
Waiting for those comments of the important places in the code for the issue and guide me a little.

Thanks!
