### ISSUE TITLE
[BUG] cant see end of the list in mobile

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/helpbuttons#999]
### 🐞 Describe the Bug

![image](https://github.com/user-attachments/assets/6bebd6ce-5f65-4d4c-8493-50e22d08462f)

on desktop:
![image](https://github.com/user-attachments/assets/14cb793d-a576-4562-9abf-29b514e29069)

---

### 🔍 Steps to Reproduce

1. Go to 'Explore'
2. Scroll down until there are no more buttons to load

my last commit on this: https://github.com/helpbuttons/helpbuttons/commit/f0cce5e5ce440c56b3246ac9026521b7b14c78f8

**Comment by watchoutfreedom** [comment]
please merge the my pull request and we can work from there
